# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
