# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_complete',
            field=models.IntegerField(default=1),
        ),
    ]
